Add term 9
tmtmtmtm/croatian-parliament-wikidata pull request #1
Opened 2016-10-27 15:11 UTC by octopusinvitro

There has been elections in 2016 and there is a new wikipedia page
listing the members of the parliament for term 9. This PR adds changes 
to scrape that page.

2016-10-27 16:48 UTC, tmtmtmtm requested changes
This links to a Morph scraper that hasn't been configured.

2016-10-27 16:53 UTC, octopusinvitro commented
@tmtmtmtm I set the scraper to auto-run :+1:

2016-11-01 08:50 UTC, tmtmtmtm commented
It's not only auto-running. Wikidata scrapers usually get configured with webhooks too…

2016-11-02 16:05 UTC, octopusinvitro commented
@tmtmtmtm I've set the webhook on morph and added the new scraper checklist

2016-11-02 16:12 UTC, tmtmtmtm approved these changes
👍

2016-11-02 16:12 UTC, merged